---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: esphome
  version: 0.0.12
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: esphome
  releaseName: esphome
  valuesFile: values.yaml

configMapGenerator:
- name: esphome-dashboard
  literals:
  - ESPHOME_DASHBOARD_USE_PING=true
- name: esphome-tz
  literals:
  - TZ=CET
