---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: lms
  version: 0.0.15
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: media
  releaseName: lms
  valuesFile: values.yaml

# configMapGenerator:
# - name: lms-env
#   behavior: create
#   literals:
#   - TZ=CET
#   - PUID=1000
#   - PGID=1000
