---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: binance-proxy
  version: 0.0.4
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: trade
  releaseName: binance-proxy
  valuesFile: values.yaml
