---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: binance-proxy

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

patches:
- target:
    kind: CustomResourceDefinition
  patch: |-
    - op: remove
      path: /metadata/labels/app.kubernetes.io~1instance
