---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: traefik
  version: 30.1.0
  repo: https://helm.traefik.io/traefik
  includeCRDs: false
  namespace: traefik
  releaseName: traefik
  valuesFile: values.yaml
