---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: authentik
  version: 2024.6.3
  repo: https://charts.goauthentik.io
  includeCRDs: true
  namespace: authentik
  releaseName: authentik
  valuesFile: values.yaml
  # valuesInline:
  #   spec:
  #     ignoreDifferences:
  #       - kind: PersistentVolume
  #         jsonPointers:
  #         - /spec/claimRef/resourceVersion
  #         - /spec/claimRef/uid
  #         - /status/lastPhaseTransitionTime
