---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/chains.yaml
- resources/middlewares.yaml
- resources/tlsoption.yaml
# - resources/servicemonitor.yaml
# - resources/tlsstore.yaml

generators:
- ksops-generator.yaml

configMapGenerator:
- name: traefik-tz
  literals:
  - TZ=CET

patches:
- patch: |-
    - op: add
      path: /subjects/0/namespace
      value: traefik
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: traefik-role-binding
    version: v1
