---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: uptime-kuma
  repo: https://jacekzubielik.github.io/jz-helm-charts
  version: 0.0.4
  includeCRDs: false
  namespace: uptime-kuma
  releaseName: uptime-kuma
  valuesFile: values.yaml
