---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: minio
  version: 5.2.0
  repo: https://charts.min.io/
  includeCRDs: true
  namespace: minio
  releaseName: minio
  valuesFile: values.yaml
