---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: home-assistant
  repo: https://jacekzubielik.github.io/jz-helm-charts
  version: 0.0.10
  includeCRDs: false
  namespace: home-assistant
  releaseName: home-assistant
  valuesFile: values.yaml

configMapGenerator:
- name: ha-tz
  literals:
  - TZ=CET
