apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: zigbee2mqtt-production
spec:
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-production
    commonName: ENC[AES256_GCM,data:invKQqcVbnQsvPm6P0FhdzhVk3oYPYEfg7o7Skk=,iv:9Vj530C2HqHYsI/Qhdc9t1l7lcbomjRADtjyZaROk14=,tag:mLMccznDT6nkm1xVZkuo8w==,type:str]
    dnsNames:
        - ENC[AES256_GCM,data:uRlZ9Mznw7rAIg2CaoCZw/Qxi9zK91JP78uKPTs=,iv:u1NJFHhKJ6OAutmEEJswERNijF8Uyk65dc4tCZAV2hk=,tag:wvQNZXwKbM/RQEJRUz8m9g==,type:str]
    secretName: zigbee2mqtt-cf-production
    duration: 2160h0m0s
    renewBefore: 720h0m0s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-22T18:24:35Z"
    mac: ENC[AES256_GCM,data:v7DGNnBDdLbdWR0ENlRfBse2htMhRdM0h2hSMoxPM9+NHTIyOUrcTNWuV5Su/Zy7F2X0CmkODxa0nB6qFQLAk+dEdb/4GHWl0a5eM4hmBAhDf8zyYHcWSOxwvstwboNRdP2N0rtyevQj+X4oyzwdtt8oth302AK76z8q5L9yH8Q=,iv:WjEe4gx2/8Y3+zcZltbmBbe/j8kE0mDTdVH5dnzfu24=,tag:f91LQWYng+bCc/noS74Xyw==,type:str]
    pgp:
        - created_at: "2024-08-22T18:24:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0R6oz1GmNjVARAAi+vFwS8cLP4fRxUzoknZX752jxkunBfqUuOCEoio3E/A
            C9zjJIQQSdwKEUndiZtS8BBfaOtl3HH/KQYi47R7qiE1s0LCc9dxBxyXN/jSP6Ra
            yR6ru/X/j6RnnYh4h5RK8P4QmR/fzPWyi00HuEPLUNKgz/E+oYwMlhUnNa/3ex13
            2iwwuH+pr3pPIBZ3ctHNT/qTS2k0qy54E43Ywo96UH5N+cZ08KM8LUqJVUh4LwW5
            9uw8iAIwd6Q1r15hD0x5LU1+QW899oZA69TMdlNAZ0jX/PO4m0V7MSA2v3OIi5Kf
            L82zJgRTZvRuT+MLz3EocNFMrlf1r7u7HMyO/HBz6s7VICjtT13HHKumCv/Ybcbk
            O5m7UVgl3EpcWAyj/tTsHNLm3xMYDvR/aD3OwMf/PT5QyFRIa67rLRyJBCII0m69
            eIp3YcZiBJTEsB0cCZqnfZWi9A1F3YwErbDGIzpeUMC21fnWjTddEJRVrVPR7eCL
            XLiQ8ik1DiCvy7IiYeGsTQ7wnX2j++axsePkToraQuzZZDTWiqVZohk7gdutGsQt
            E9mGGGBYfKE9EjOG6eriE4qDlwbL5hSo1R8KL9Ez8ibUdb+ShdJVFdLWY16AEGbz
            xmmBy5XdXEp9u1fDWZFY+KREzWM+3xOnckpKvt9S/eNfkpJQ6JwpEvf9ZAub4OTS
            XgF/j3Y7/O4XR1J4dT5DQggzPerIMry2cv/HZxhhUhKquoKZoM+UWDeDwErunWp4
            u9HVNzsS68k+naTTm1LrEeSmoLBpQT5q0aKiwkk8mo4veoXDRMQeA3IOqWMBVTg=
            =zzt/
            -----END PGP MESSAGE-----
          fp: 6D3FE55384B558E06A1BA364586EFA784A32C981
    encrypted_regex: ^(ca.crt|client.crt|client.key|externalName|external-dns.alpha.kubernetes.io/hostname|sans|main|match|external-dns.alpha.kubernetes.io/target|dnsNames|commonName|stringData|dnsNames|email|accessKeyID|region|hostedZoneID|role|dnsZones)$
    version: 3.8.1
