---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: zigbee2mqtt
  version: 0.0.10
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: zigbee2mqtt
  releaseName: zigbee2mqtt
  valuesFile: values.yaml

# configMapGenerator:
# - name: zigbee2mqtt-tz
#   literals:
#   - TZ=CET
