---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- ../../base

helmCharts:
- name: longhorn
  version: 1.7.0
  repo: https://charts.longhorn.io
  includeCRDs: true
  namespace: longhorn-system
  releaseName: longhorn
  valuesFile: values.yaml
