---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/backing-image.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/volume.yaml
# - resources/volume.snapshot.yaml

# generators:
# - ksops-generator.yaml

# generatorOptions:
#   disableNameSuffixHash: true
