---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: mosquitto
  version: 0.0.5
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: mosquitto
  releaseName: mosquitto
  valuesFile: values.yaml
