---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/pv.yaml
- resources/pvc.yaml
- resources/service-proxy.yaml

# generators:
# - ksops-generator.yaml
