---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/deployment.yaml
- resources/service.yaml
- resources/servicemonitor.yaml
# - secrets/secret.yaml
# - resources/podmonitor.yaml

generators:
- ksops-generator.yaml

configMapGenerator:
- name: mktxp-exporter-tz
  literals:
  - TZ=CET
