---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: kube-prometheus-stack
  version: 62.1.0
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: false
  namespace: monitoring
  releaseName: kube-prometheus-stack
  valuesFile: values.yaml
  valuesInline:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
    prometheusOperator:
      admissionWebhooks:
        failurePolicy: Ignore
    # spec:
    #   ignoreDifferences:
    #   - kind: PersistentVolume
    #     jsonPointers:
    #     - /spec/claimRef/resourceVersion
    #     - /spec/claimRef/uid
    #     - /status/lastPhaseTransitionTime
