---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: cert-manager
  version: v1.14.4 # 1.15.2
  repo: https://charts.jetstack.io
  includeCRDs: false
  namespace: cert-manager
  releaseName: cert-manager
  valuesFile: values.yaml
